"""Format converters: JSONL ⟷ HuggingFace-style splits."""

from __future__ import annotations

import json
from pathlib import Path

from cocapn_training.dataset import Dataset


def jsonl_to_hf(jsonl_path: str, output_dir: str) -> None:
    """Convert a single JSONL file into HuggingFace-style splits.

    Writes *output_dir*/{train.jsonl, val.jsonl, test.jsonl, dataset_card.md}.
    """
    ds = Dataset.load_jsonl(jsonl_path)
    train_ds, val_ds, test_ds = ds.split(train=0.8, val=0.1, test=0.1, seed=42)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    train_ds.save_jsonl(out / "train.jsonl")
    val_ds.save_jsonl(out / "val.jsonl")
    test_ds.save_jsonl(out / "test.jsonl")

    card = f"""# Dataset Card

Generated by cocapn-training.

## Splits

| Split | Size |
|-------|------|
| train | {train_ds.size} |
| val   | {val_ds.size} |
| test  | {test_ds.size} |

## Domains

{', '.join(ds.domains) or 'N/A'}
"""
    (out / "dataset_card.md").write_text(card, encoding="utf-8")


def hf_to_jsonl(hf_dir: str, output_path: str) -> None:
    """Combine HuggingFace-style splits back into a single JSONL file."""
    base = Path(hf_dir)
    tiles: list[dict] = []
    for name in ("train.jsonl", "val.jsonl", "test.jsonl"):
        path = base / name
        if path.exists():
            ds = Dataset.load_jsonl(path)
            tiles.extend(ds.to_list())
    Dataset(tiles).save_jsonl(output_path)


def tiles_to_jsonl(tiles_list: list[dict], output_path: str) -> None:
    """Write a raw list of tiles to a JSONL file."""
    Dataset(tiles_list).save_jsonl(output_path)
